config/routes.rb
Rails.application.routes.draw do

  root 'github_globals#index'

  resources :github_globals, only: [:index]
  resources :github_apis, only: [:search, :index]
  resources :keywords, only: [:index]
  resources :users, only: [:index]

  match '/keywords/add',        to: 'keywords#add',         via: 'post'
  match '/keywords/get_data',   to: 'keywords#get_data',    via: 'get'
  match '/keywords/delete',     to: 'keywords#delete',      via: 'get'

  match '/users/add_user',    to: 'users#add_user',         via: 'post'
  match '/users/get_user',    to: 'users#get_user',         via: 'get'
  match '/users/delete_user', to: 'users#delete_user',      via: 'get'

end

app/models/github_current.rb
 # create_table "github_currents", force: :cascade do |t|
 #    t.string   "user_name",     limit: 255
 #    t.integer  "keywords_id",   limit: 4
 #    t.string   "repository",    limit: 255
 #    t.string   "file_location", limit: 255
 #    t.datetime "created_at",                null: false
 #    t.datetime "updated_at",                null: false
 #  end


class GithubCurrent < ActiveRecord::Base
	
end

app/models/github_stable.rb
  # create_table "github_stables", force: :cascade do |t|
  #   t.string   "user_name",     limit: 255
  #   t.integer  "keywords_id",   limit: 4
  #   t.string   "repository",    limit: 255
  #   t.string   "file_location", limit: 255
  #   t.datetime "created_at",                null: false
  #   t.datetime "updated_at",                null: false
  # end

 
class GithubStable < ActiveRecord::Base
	
end

app/models/keyword.rb
 # create_table "keywords", force: :cascade do |t|
 #    t.string   "keyword",    limit: 255
 #    t.datetime "created_at",             null: false
 #    t.datetime "updated_at",             null: false
 #  end

class Keyword < ActiveRecord::Base
	validates :keyword , presence: true
end

app/models/user.rb
  # create_table "users", force: :cascade do |t|
  #   t.string   "user",       limit: 255
  #   t.datetime "created_at",             null: false
  #   t.datetime "updated_at",             null: false
  # end

class User < ActiveRecord::Base
	validates :user, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/github_apis_controller.rb
require './lib/api'

class GithubApisController < ApplicationController
  include Api

  def search
  end

  def index
  	#@file_name,@html_url,@repository,@key,@user,@user_link = [],[],[],[],[],[],[]
    @data = {
      file_name: [],
      html_url: [],
      repository: [],
      key: [],
      user: [],
      user_link: []
    }
  	# @path = []
  	@count = 0
    # get_data = github_search("https://api.github.com/search/code?q=ruby+user:twinks14")
    fetch_data(@data) 
  end

  def fetch_data data
    keywords = Keyword.all.pluck(:keyword)
    users = User.all.pluck(:user)
     users.each do |user| 
      keywords.each do |keyword|
        sleep(3)
        get_data = Api.github_search("https://api.github.com/search/code?q=#{keyword}+user:#{user}")
        if !get_data.blank? &&  get_data["items"].count != 0 
          @count += get_data["items"].count
          get_data["items"].each_with_index do |hash,index|
            data[:user] << user
            data[:key] << keyword
            data[:file_name] << get_data["items"][index]["name"]
            # @path << get_data["items"][index]["path"]
            data[:html_url] << get_data["items"][index]["html_url"]
            data[:repository] << get_data["items"][index]["repository"]["name"]
            data[:user_link] << get_data["items"][index]["repository"]["owner"]["html_url"]
          end
        end
      end
    end
  end
end

app/controllers/github_globals_controller.rb
class GithubGlobalsController < ApplicationController
  def index
  	 @data = {
      file_name: [],
      file_location: [],
      repository: [],
      repository_link: [],
      key: [],
      user: [],
      user_link: []
    }
    link = 'http://github.com'
  	@global_search = GithubStable.all
  	@global_search.each do |r|
  		@data[:user] << r.user_name.tr('/', '')
  		@data[:user_link] << link + r.user_name
  		@data[:repository] << r.repository.split('/')[-1]
  		@data[:repository_link] << link + r.repository
  		@data[:file_name] <<  r.file_location.split('/')[-1]
  		@data[:file_location] << link + r.file_location
  		@data[:key] << r.keyword
  	end
  	@count = @data[:user].count
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController

  def index
  	#render json: Keyword.all.to_json
  end

  def get_data
  		render json: Keyword.all.to_json
  end

  def add
    @key = Keyword.new({:keyword => "#{params[:keyword].strip}"}) 
    @key.save! 
    render json: Keyword.all.to_json
  end

  def delete
  	 @key = Keyword.find("#{params[:id]}")
    @key.destroy
    render json: Keyword.all.to_json
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def get_user
  	render json: User.all.to_json
  end

  def add_user
  	@user = User.new({:user => "#{params[:user].strip}"}) 
    @user.save! 
    render json: User.all.to_json
  end

  def delete_user
  	@user = User.find("#{params[:id]}")
    @user.destroy
    render json: User.all.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/github_apis_helper.rb
module GithubApisHelper
end

app/helpers/github_globals_helper.rb
module GithubGlobalsHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/github_apis/index.html.erb
<h1>Github Search</h1>
<div id="gethub_search"> 
<% if @count != 0 %>
    <table class="table table-striped datatable">
    	<tr>
    		<th>No</th>
    		<th>User</th>
    		<th>Keyword</th>
    		<th>Repository</th>
    		<th>URL</th>
    	</tr>
    	<% @count.times do |index| %>
    	<tr>
    		<td><%= index+1 %></td>
    		<td><%= link_to @data[:user][index], @data[:user_link][index], :target => "_blank" %></td>
    		<td><%= @data[:key][index] %></td>
    		<td><%= @data[:repository][index] %></td>
    		<td><%= link_to @data[:file_name][index], @data[:html_url][index], :target => "_blank" %></td>
    	</tr>
    	<% end %>
    </table> 
<%else%>
    <br />
    <h3>No match found..!!!</h3>
    <p>
    <%= link_to "Click to add new Keyword", keywords_path, :target => "_blank" %> | 
    <%= link_to "Click to add new User", users_path, :target => "_blank" %>
    </p>
<% end %>
</div>

<!-- <p>Total Count = <%= @total_count %> </p>

<p>File Name =  <%= @file_name %></p>

<p>Path =  <%= @path %></p>

<p>URL =  <%= @html_url %></p>

<p>repository =  <%= @repository %></p> -->

app/views/github_apis/search.html.erb
<h1>GithubApis#search</h1>
<p>Find me in app/views/github_apis/search.html.erb</p>

app/views/github_globals/index.html.erb
<h1>Global Search</h1>
<div id="github_search" style='width:95%;padding-top:30px;padding-bottom:10px;'>
  <% if @count != 0 %>
    <table id='github_global' class="table table-striped" style='width:100%;border:1px solid;'>
      <thead>
        <tr>
          <th>No</th>
          <th>User</th>
          <th>Match</th>
          <th>Repository</th>
          <th>URL</th>
        </tr>
      </thead>
      <tbody>
        <% @count.times do |i| %>
            <tr>
              <td><%= i+1 %></td>
              <td><%= link_to @data[:user][i], @data[:user_link][i], :target => "_blank" %></td>
              <td><%= @data[:key][i] %></td>
              <td><%= link_to @data[:repository][i], @data[:repository_link][i], :target => "_blank" %></td>
              <td><%= link_to @data[:file_name][i], @data[:file_location][i], :target => "_blank" %></td>
            </tr>
        <% end %>
      </tbody>
    </table> 
  <%else%>
    <br />
    <h3>No match found..!!!</h3>
    <p><%= link_to "Click to add new Keyword", keywords_path, :target => "_blank" %></p>
  <% end %>
</div>

app/views/keywords/index.html.erb
<form id="form1" enctype="multipart/form-data" remote="true" accept-charset="ISO-8859-1">
 <div class="row">
  <div id="profile">
  <h2><p>Add KeyWords</p></h2>
    <table>
      <tr>
      <td><%= text_field_tag :keyword%>
      <input type="button" value="Add" id="add_keyword" class= "btn btn-xs btn-primary" /></td>
      <td><div id="error"></div></td>
      </tr>
    </table>
    <br />
      <div id="keywords_list"> 
        <table class="table table-striped datatable"></table> 
    </div>
   </div>
 </div>
</form>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to '<b>Github Search</b>'.html_safe, root_url, :class => "navbar-brand" %>
    </div>
    <div class="navbar-header-right" , data-no-turbolink>
      <%= link_to "Global Search", github_globals_path, :class => "navbar-brand" %>
      <%= link_to "Internal Search", github_apis_path, :class => "navbar-brand" %>
      <%= link_to "Keyword", keywords_url, :class => "navbar-brand" %>
      <%= link_to "User", users_url, :class => "navbar-brand" %>
      
      <%#= link_to "Bengaluru", visits_url(location: 'Bengaluru'), :class => "navbar-brand" %>
      <%#= link_to "Kolkata", visits_url(location: 'Kolkata'), :class => "navbar-brand" %>
      <%#= link_to "Gurgaon", visits_url(location: 'Gurgaon'), :class => "navbar-brand" %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Github Search</title>
 <!--  <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 -->
  <%= stylesheet_link_tag "application", params[:controller], :media => "all" %>
  <%= javascript_include_tag "application", params[:controller] %>
  <%= csrf_meta_tags %>
</head>
<body>
 <!-- <div class="container"> -->
  <%= render 'layouts/header' %>
  <%= yield %> 
 <!--  </div> -->
</body>
</html>

app/views/send_search_mail/send_search_mail.html.erb
<p>Hello Team,</p>
<p>
	Please find attachment for github search result.   
</p>

<p>Thank you,<br>Twinkal Savani</p>
<p style="color:grey"><small>*** This is a system generated email, please do not reply ***</small></p>

app/views/users/index.html.erb
<form id="form" enctype="multipart/form-data" remote="true" accept-charset="ISO-8859-1">
 <div class="row">
  <div id="profile">
  <h2><p>Add Users</p></h2>
    <table>
      <tr>
      <td><%= text_field_tag :user %>
      <input type="button" value="Add" id="add_user" class= "btn btn-xs btn-primary" /></td>
      <td><div id="error"></div></td>
      </tr>
    </table>
    <br />
      <div id="users_list"> 
        <table class="table table-striped datatable"></table> 
    </div>
   </div>
 </div>
</form>